#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 143
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_extends = 1,
  anon_sym_include = 2,
  anon_sym_block = 3,
  anon_sym_if = 4,
  anon_sym_elseif = 5,
  anon_sym_else = 6,
  aux_sym_condition_token1 = 7,
  sym_tag_name = 8,
  sym_class_or_id = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_EQ = 12,
  sym_attribute_name = 13,
  sym_quoted_attribute_value = 14,
  sym_unquoted_attribute_value = 15,
  sym__space = 16,
  sym_identifier = 17,
  sym__newline = 18,
  sym__indent = 19,
  sym__dedent = 20,
  sym_source_file = 21,
  sym_block_expansion = 22,
  sym_extends_statement = 23,
  sym_include_statement = 24,
  sym_block_statement = 25,
  sym_tag = 26,
  sym_conditional = 27,
  sym_if_statement = 28,
  sym_else_if_statement = 29,
  sym_else_statement = 30,
  sym_condition = 31,
  sym_attributes = 32,
  sym_attribute = 33,
  sym_inline_text = 34,
  sym_children = 35,
  sym__children_choice = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_tag_repeat1 = 38,
  aux_sym_conditional_repeat1 = 39,
  aux_sym_attributes_repeat1 = 40,
  aux_sym_children_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_extends] = "extends",
  [anon_sym_include] = "include",
  [anon_sym_block] = "block",
  [anon_sym_if] = "if",
  [anon_sym_elseif] = "else if",
  [anon_sym_else] = "else",
  [aux_sym_condition_token1] = "condition_token1",
  [sym_tag_name] = "tag_name",
  [sym_class_or_id] = "class_or_id",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_unquoted_attribute_value] = "unquoted_attribute_value",
  [sym__space] = "_space",
  [sym_identifier] = "identifier",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_source_file] = "source_file",
  [sym_block_expansion] = "block_expansion",
  [sym_extends_statement] = "extends_statement",
  [sym_include_statement] = "include_statement",
  [sym_block_statement] = "block_statement",
  [sym_tag] = "tag",
  [sym_conditional] = "conditional",
  [sym_if_statement] = "if_statement",
  [sym_else_if_statement] = "else_if_statement",
  [sym_else_statement] = "else_statement",
  [sym_condition] = "condition",
  [sym_attributes] = "attributes",
  [sym_attribute] = "attribute",
  [sym_inline_text] = "inline_text",
  [sym_children] = "children",
  [sym__children_choice] = "_children_choice",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym_conditional_repeat1] = "conditional_repeat1",
  [aux_sym_attributes_repeat1] = "attributes_repeat1",
  [aux_sym_children_repeat1] = "children_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_block] = anon_sym_block,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [aux_sym_condition_token1] = aux_sym_condition_token1,
  [sym_tag_name] = sym_tag_name,
  [sym_class_or_id] = sym_class_or_id,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_unquoted_attribute_value] = sym_unquoted_attribute_value,
  [sym__space] = sym__space,
  [sym_identifier] = sym_identifier,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_source_file] = sym_source_file,
  [sym_block_expansion] = sym_block_expansion,
  [sym_extends_statement] = sym_extends_statement,
  [sym_include_statement] = sym_include_statement,
  [sym_block_statement] = sym_block_statement,
  [sym_tag] = sym_tag,
  [sym_conditional] = sym_conditional,
  [sym_if_statement] = sym_if_statement,
  [sym_else_if_statement] = sym_else_if_statement,
  [sym_else_statement] = sym_else_statement,
  [sym_condition] = sym_condition,
  [sym_attributes] = sym_attributes,
  [sym_attribute] = sym_attribute,
  [sym_inline_text] = sym_inline_text,
  [sym_children] = sym_children,
  [sym__children_choice] = sym__children_choice,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym_conditional_repeat1] = aux_sym_conditional_repeat1,
  [aux_sym_attributes_repeat1] = aux_sym_attributes_repeat1,
  [aux_sym_children_repeat1] = aux_sym_children_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_condition_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class_or_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym_extends_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_include_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_text] = {
    .visible = true,
    .named = true,
  },
  [sym_children] = {
    .visible = true,
    .named = true,
  },
  [sym__children_choice] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conditional_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_children_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 2,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 2,
  [13] = 3,
  [14] = 5,
  [15] = 15,
  [16] = 16,
  [17] = 9,
  [18] = 5,
  [19] = 19,
  [20] = 6,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 9,
  [32] = 32,
  [33] = 33,
  [34] = 19,
  [35] = 35,
  [36] = 16,
  [37] = 15,
  [38] = 22,
  [39] = 21,
  [40] = 40,
  [41] = 29,
  [42] = 42,
  [43] = 15,
  [44] = 26,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 27,
  [49] = 49,
  [50] = 50,
  [51] = 24,
  [52] = 52,
  [53] = 53,
  [54] = 32,
  [55] = 28,
  [56] = 56,
  [57] = 33,
  [58] = 25,
  [59] = 59,
  [60] = 23,
  [61] = 30,
  [62] = 19,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 23,
  [67] = 53,
  [68] = 33,
  [69] = 26,
  [70] = 29,
  [71] = 49,
  [72] = 65,
  [73] = 64,
  [74] = 35,
  [75] = 27,
  [76] = 32,
  [77] = 35,
  [78] = 78,
  [79] = 50,
  [80] = 78,
  [81] = 78,
  [82] = 28,
  [83] = 47,
  [84] = 40,
  [85] = 63,
  [86] = 25,
  [87] = 47,
  [88] = 24,
  [89] = 78,
  [90] = 56,
  [91] = 45,
  [92] = 30,
  [93] = 46,
  [94] = 42,
  [95] = 52,
  [96] = 59,
  [97] = 97,
  [98] = 47,
  [99] = 99,
  [100] = 52,
  [101] = 101,
  [102] = 102,
  [103] = 40,
  [104] = 45,
  [105] = 105,
  [106] = 50,
  [107] = 46,
  [108] = 42,
  [109] = 109,
  [110] = 109,
  [111] = 111,
  [112] = 109,
  [113] = 111,
  [114] = 114,
  [115] = 111,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 117,
  [120] = 116,
  [121] = 121,
  [122] = 116,
  [123] = 123,
  [124] = 121,
  [125] = 125,
  [126] = 118,
  [127] = 127,
  [128] = 125,
  [129] = 121,
  [130] = 130,
  [131] = 131,
  [132] = 123,
  [133] = 131,
  [134] = 134,
  [135] = 131,
  [136] = 127,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#' ||
          lookahead == '.') ADVANCE(10);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == ')') ADVANCE(48);
      if (lookahead == '=') ADVANCE(49);
      if (lookahead == 'b') ADVANCE(35);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3)
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(54);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4)
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == 'f') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9)
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 11:
      if (eof) ADVANCE(16);
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == '#' ||
          lookahead == '.') ADVANCE(10);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == 'b') ADVANCE(35);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(14)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 12:
      if (eof) ADVANCE(16);
      if (lookahead == ' ') ADVANCE(55);
      if (lookahead == '#' ||
          lookahead == '.') ADVANCE(10);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == 'b') ADVANCE(35);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == 'i') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(15)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 13:
      if (eof) ADVANCE(16);
      if (lookahead == 'b') ADVANCE(35);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == 'i') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 14:
      if (eof) ADVANCE(16);
      if (lookahead == '#' ||
          lookahead == '.') ADVANCE(10);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == 'b') ADVANCE(35);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '#' ||
          lookahead == '.') ADVANCE(10);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == 'b') ADVANCE(35);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == 'i') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_extends);
      if (lookahead == '-') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_include);
      if (lookahead == '-') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_block);
      if (lookahead == '-') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == ' ') ADVANCE(7);
      if (lookahead == '-') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_condition_token1);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_condition_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'c') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'c') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'd') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'd') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'f') ADVANCE(20);
      if (lookahead == 'n') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'f') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'k') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'l') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'l') ADVANCE(40);
      if (lookahead == 'x') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'l') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'o') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 's') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 's') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 't') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == 'x') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_class_or_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_quoted_attribute_value);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_quoted_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ')') ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_unquoted_attribute_value);
      if (lookahead == '"') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ')') ADVANCE(2);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_unquoted_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ')') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == ' ') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 11, .external_lex_state = 1},
  [3] = {.lex_state = 11, .external_lex_state = 1},
  [4] = {.lex_state = 12, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 12, .external_lex_state = 1},
  [9] = {.lex_state = 11, .external_lex_state = 1},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 12, .external_lex_state = 3},
  [13] = {.lex_state = 12, .external_lex_state = 3},
  [14] = {.lex_state = 13, .external_lex_state = 2},
  [15] = {.lex_state = 11, .external_lex_state = 1},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 12, .external_lex_state = 1},
  [18] = {.lex_state = 13, .external_lex_state = 2},
  [19] = {.lex_state = 11, .external_lex_state = 1},
  [20] = {.lex_state = 13, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 1},
  [24] = {.lex_state = 0, .external_lex_state = 1},
  [25] = {.lex_state = 0, .external_lex_state = 1},
  [26] = {.lex_state = 11, .external_lex_state = 1},
  [27] = {.lex_state = 0, .external_lex_state = 1},
  [28] = {.lex_state = 0, .external_lex_state = 1},
  [29] = {.lex_state = 11, .external_lex_state = 1},
  [30] = {.lex_state = 0, .external_lex_state = 1},
  [31] = {.lex_state = 12, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 1},
  [33] = {.lex_state = 0, .external_lex_state = 1},
  [34] = {.lex_state = 12, .external_lex_state = 1},
  [35] = {.lex_state = 0, .external_lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 12, .external_lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 12, .external_lex_state = 1},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 12, .external_lex_state = 3},
  [44] = {.lex_state = 12, .external_lex_state = 1},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 13, .external_lex_state = 1},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 13, .external_lex_state = 1},
  [52] = {.lex_state = 0, .external_lex_state = 2},
  [53] = {.lex_state = 0, .external_lex_state = 2},
  [54] = {.lex_state = 13, .external_lex_state = 1},
  [55] = {.lex_state = 13, .external_lex_state = 1},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 13, .external_lex_state = 1},
  [58] = {.lex_state = 13, .external_lex_state = 1},
  [59] = {.lex_state = 0, .external_lex_state = 2},
  [60] = {.lex_state = 13, .external_lex_state = 1},
  [61] = {.lex_state = 13, .external_lex_state = 1},
  [62] = {.lex_state = 12, .external_lex_state = 3},
  [63] = {.lex_state = 0, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 13, .external_lex_state = 3},
  [67] = {.lex_state = 0, .external_lex_state = 4},
  [68] = {.lex_state = 13, .external_lex_state = 3},
  [69] = {.lex_state = 12, .external_lex_state = 3},
  [70] = {.lex_state = 12, .external_lex_state = 3},
  [71] = {.lex_state = 0, .external_lex_state = 4},
  [72] = {.lex_state = 0, .external_lex_state = 4},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 13, .external_lex_state = 1},
  [75] = {.lex_state = 13, .external_lex_state = 3},
  [76] = {.lex_state = 13, .external_lex_state = 5},
  [77] = {.lex_state = 13, .external_lex_state = 3},
  [78] = {.lex_state = 8, .external_lex_state = 4},
  [79] = {.lex_state = 13, .external_lex_state = 2},
  [80] = {.lex_state = 8, .external_lex_state = 4},
  [81] = {.lex_state = 8, .external_lex_state = 4},
  [82] = {.lex_state = 13, .external_lex_state = 5},
  [83] = {.lex_state = 13, .external_lex_state = 2},
  [84] = {.lex_state = 13, .external_lex_state = 2},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 13, .external_lex_state = 5},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 13, .external_lex_state = 5},
  [89] = {.lex_state = 8, .external_lex_state = 4},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 13, .external_lex_state = 2},
  [92] = {.lex_state = 13, .external_lex_state = 5},
  [93] = {.lex_state = 13, .external_lex_state = 2},
  [94] = {.lex_state = 13, .external_lex_state = 2},
  [95] = {.lex_state = 13, .external_lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 13, .external_lex_state = 4},
  [98] = {.lex_state = 13},
  [99] = {.lex_state = 13},
  [100] = {.lex_state = 13},
  [101] = {.lex_state = 13},
  [102] = {.lex_state = 13},
  [103] = {.lex_state = 13},
  [104] = {.lex_state = 13},
  [105] = {.lex_state = 13},
  [106] = {.lex_state = 13},
  [107] = {.lex_state = 13},
  [108] = {.lex_state = 13},
  [109] = {.lex_state = 4},
  [110] = {.lex_state = 4},
  [111] = {.lex_state = 4},
  [112] = {.lex_state = 4},
  [113] = {.lex_state = 4},
  [114] = {.lex_state = 4},
  [115] = {.lex_state = 4},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 0, .external_lex_state = 5},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0, .external_lex_state = 5},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 0, .external_lex_state = 5},
  [124] = {.lex_state = 1},
  [125] = {.lex_state = 1},
  [126] = {.lex_state = 1},
  [127] = {.lex_state = 0, .external_lex_state = 5},
  [128] = {.lex_state = 1},
  [129] = {.lex_state = 1},
  [130] = {.lex_state = 4},
  [131] = {.lex_state = 1},
  [132] = {.lex_state = 0, .external_lex_state = 5},
  [133] = {.lex_state = 1},
  [134] = {.lex_state = 3},
  [135] = {.lex_state = 1},
  [136] = {.lex_state = 0, .external_lex_state = 5},
  [137] = {.lex_state = 0, .external_lex_state = 5},
  [138] = {.lex_state = 9},
  [139] = {.lex_state = 9},
  [140] = {.lex_state = 9},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_block] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [sym_class_or_id] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_quoted_attribute_value] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(142),
    [sym_block_expansion] = STATE(11),
    [sym_extends_statement] = STATE(99),
    [sym_include_statement] = STATE(99),
    [sym_block_statement] = STATE(99),
    [sym_tag] = STATE(11),
    [sym_conditional] = STATE(11),
    [sym_if_statement] = STATE(39),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_extends] = ACTIONS(5),
    [anon_sym_include] = ACTIONS(7),
    [anon_sym_block] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [sym_tag_name] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(19), 1,
      sym_class_or_id,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym__space,
    ACTIONS(25), 1,
      sym__newline,
    ACTIONS(27), 1,
      sym__indent,
    STATE(3), 1,
      aux_sym_tag_repeat1,
    STATE(19), 1,
      sym_attributes,
    STATE(40), 1,
      sym_children,
    ACTIONS(15), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(17), 7,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      sym_tag_name,
  [38] = 10,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym__indent,
    ACTIONS(33), 1,
      sym_class_or_id,
    ACTIONS(35), 1,
      sym__space,
    ACTIONS(37), 1,
      sym__newline,
    STATE(9), 1,
      aux_sym_tag_repeat1,
    STATE(15), 1,
      sym_attributes,
    STATE(50), 1,
      sym_children,
    ACTIONS(29), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(31), 7,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      sym_tag_name,
  [76] = 10,
    ACTIONS(39), 1,
      sym_class_or_id,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym__space,
    ACTIONS(45), 1,
      sym__newline,
    ACTIONS(47), 1,
      sym__indent,
    STATE(17), 1,
      aux_sym_tag_repeat1,
    STATE(37), 1,
      sym_attributes,
    STATE(79), 1,
      sym_children,
    ACTIONS(29), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(31), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [112] = 8,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(55), 1,
      sym_tag_name,
    ACTIONS(57), 1,
      sym__newline,
    ACTIONS(59), 1,
      sym__dedent,
    STATE(21), 1,
      sym_if_statement,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(51), 4,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_else,
    STATE(6), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [144] = 7,
    ACTIONS(65), 1,
      anon_sym_if,
    ACTIONS(68), 1,
      sym_tag_name,
    ACTIONS(71), 1,
      sym__newline,
    STATE(21), 1,
      sym_if_statement,
    ACTIONS(61), 3,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(63), 4,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_else,
    STATE(6), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [174] = 8,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(55), 1,
      sym_tag_name,
    ACTIONS(57), 1,
      sym__newline,
    ACTIONS(74), 1,
      sym__dedent,
    STATE(21), 1,
      sym_if_statement,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(51), 4,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_else,
    STATE(6), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [206] = 10,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym__indent,
    ACTIONS(76), 1,
      sym_class_or_id,
    ACTIONS(78), 1,
      sym__space,
    ACTIONS(80), 1,
      sym__newline,
    STATE(4), 1,
      aux_sym_tag_repeat1,
    STATE(34), 1,
      sym_attributes,
    STATE(84), 1,
      sym_children,
    ACTIONS(15), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(17), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [242] = 4,
    ACTIONS(86), 1,
      sym_class_or_id,
    STATE(9), 1,
      aux_sym_tag_repeat1,
    ACTIONS(82), 5,
      sym__newline,
      sym__indent,
      sym__dedent,
      ts_builtin_sym_end,
      sym__space,
    ACTIONS(84), 8,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      sym_tag_name,
      anon_sym_LPAREN,
  [266] = 9,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 1,
      anon_sym_extends,
    ACTIONS(94), 1,
      anon_sym_include,
    ACTIONS(97), 1,
      anon_sym_block,
    ACTIONS(100), 1,
      anon_sym_if,
    ACTIONS(103), 1,
      sym_tag_name,
    STATE(39), 1,
      sym_if_statement,
    STATE(99), 3,
      sym_extends_statement,
      sym_include_statement,
      sym_block_statement,
    STATE(10), 4,
      sym_block_expansion,
      sym_tag,
      sym_conditional,
      aux_sym_source_file_repeat1,
  [299] = 9,
    ACTIONS(5), 1,
      anon_sym_extends,
    ACTIONS(7), 1,
      anon_sym_include,
    ACTIONS(9), 1,
      anon_sym_block,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_tag_name,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      sym_if_statement,
    STATE(99), 3,
      sym_extends_statement,
      sym_include_statement,
      sym_block_statement,
    STATE(10), 4,
      sym_block_expansion,
      sym_tag,
      sym_conditional,
      aux_sym_source_file_repeat1,
  [332] = 10,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 1,
      sym_class_or_id,
    ACTIONS(110), 1,
      anon_sym_LPAREN,
    ACTIONS(112), 1,
      sym__space,
    ACTIONS(114), 1,
      sym__newline,
    ACTIONS(116), 1,
      sym__indent,
    STATE(13), 1,
      aux_sym_tag_repeat1,
    STATE(62), 1,
      sym_attributes,
    STATE(103), 1,
      sym_children,
    ACTIONS(17), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [367] = 10,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 1,
      anon_sym_LPAREN,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(118), 1,
      sym_class_or_id,
    ACTIONS(120), 1,
      sym__space,
    ACTIONS(122), 1,
      sym__newline,
    STATE(31), 1,
      aux_sym_tag_repeat1,
    STATE(43), 1,
      sym_attributes,
    STATE(106), 1,
      sym_children,
    ACTIONS(31), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [402] = 8,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(124), 1,
      sym_tag_name,
    ACTIONS(126), 1,
      sym__newline,
    ACTIONS(128), 1,
      sym__dedent,
    STATE(21), 1,
      sym_if_statement,
    ACTIONS(51), 3,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
    STATE(20), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [432] = 6,
    ACTIONS(27), 1,
      sym__indent,
    ACTIONS(134), 1,
      sym__space,
    ACTIONS(136), 1,
      sym__newline,
    STATE(45), 1,
      sym_children,
    ACTIONS(130), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(132), 7,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      sym_tag_name,
  [458] = 5,
    ACTIONS(142), 1,
      anon_sym_elseif,
    ACTIONS(144), 1,
      anon_sym_else,
    ACTIONS(138), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    STATE(22), 3,
      sym_else_if_statement,
      sym_else_statement,
      aux_sym_conditional_repeat1,
    ACTIONS(140), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [482] = 4,
    ACTIONS(146), 1,
      sym_class_or_id,
    STATE(17), 1,
      aux_sym_tag_repeat1,
    ACTIONS(82), 5,
      sym__newline,
      sym__indent,
      sym__dedent,
      ts_builtin_sym_end,
      sym__space,
    ACTIONS(84), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
      anon_sym_LPAREN,
  [504] = 8,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(124), 1,
      sym_tag_name,
    ACTIONS(126), 1,
      sym__newline,
    ACTIONS(149), 1,
      sym__dedent,
    STATE(21), 1,
      sym_if_statement,
    ACTIONS(51), 3,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
    STATE(20), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [534] = 6,
    ACTIONS(27), 1,
      sym__indent,
    ACTIONS(35), 1,
      sym__space,
    ACTIONS(37), 1,
      sym__newline,
    STATE(50), 1,
      sym_children,
    ACTIONS(29), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(31), 7,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      sym_tag_name,
  [560] = 7,
    ACTIONS(65), 1,
      anon_sym_if,
    ACTIONS(151), 1,
      sym_tag_name,
    ACTIONS(154), 1,
      sym__newline,
    STATE(21), 1,
      sym_if_statement,
    ACTIONS(61), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(63), 3,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
    STATE(20), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [588] = 5,
    ACTIONS(142), 1,
      anon_sym_elseif,
    ACTIONS(144), 1,
      anon_sym_else,
    ACTIONS(157), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    STATE(16), 3,
      sym_else_if_statement,
      sym_else_statement,
      aux_sym_conditional_repeat1,
    ACTIONS(159), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [612] = 5,
    ACTIONS(165), 1,
      anon_sym_elseif,
    ACTIONS(168), 1,
      anon_sym_else,
    ACTIONS(161), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    STATE(22), 3,
      sym_else_if_statement,
      sym_else_statement,
      aux_sym_conditional_repeat1,
    ACTIONS(163), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [636] = 5,
    ACTIONS(27), 1,
      sym__indent,
    ACTIONS(175), 1,
      sym__newline,
    STATE(52), 1,
      sym_children,
    ACTIONS(171), 3,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(173), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [659] = 4,
    ACTIONS(27), 1,
      sym__indent,
    STATE(50), 1,
      sym_children,
    ACTIONS(29), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(31), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [680] = 4,
    ACTIONS(27), 1,
      sym__indent,
    STATE(46), 1,
      sym_children,
    ACTIONS(177), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(179), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [701] = 2,
    ACTIONS(181), 5,
      sym__newline,
      sym__indent,
      sym__dedent,
      ts_builtin_sym_end,
      sym__space,
    ACTIONS(183), 7,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      sym_tag_name,
  [718] = 5,
    ACTIONS(27), 1,
      sym__indent,
    ACTIONS(136), 1,
      sym__newline,
    STATE(45), 1,
      sym_children,
    ACTIONS(130), 3,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(132), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [741] = 4,
    ACTIONS(27), 1,
      sym__indent,
    STATE(45), 1,
      sym_children,
    ACTIONS(130), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(132), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [762] = 2,
    ACTIONS(185), 5,
      sym__newline,
      sym__indent,
      sym__dedent,
      ts_builtin_sym_end,
      sym__space,
    ACTIONS(187), 7,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      sym_tag_name,
  [779] = 4,
    ACTIONS(27), 1,
      sym__indent,
    STATE(52), 1,
      sym_children,
    ACTIONS(171), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(173), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [800] = 4,
    ACTIONS(189), 1,
      sym_class_or_id,
    STATE(31), 1,
      aux_sym_tag_repeat1,
    ACTIONS(82), 4,
      sym__newline,
      sym__indent,
      ts_builtin_sym_end,
      sym__space,
    ACTIONS(84), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
      anon_sym_LPAREN,
  [821] = 4,
    ACTIONS(27), 1,
      sym__indent,
    STATE(42), 1,
      sym_children,
    ACTIONS(192), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(194), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [842] = 5,
    ACTIONS(27), 1,
      sym__indent,
    ACTIONS(196), 1,
      sym__newline,
    STATE(42), 1,
      sym_children,
    ACTIONS(192), 3,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(194), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [865] = 6,
    ACTIONS(43), 1,
      sym__space,
    ACTIONS(45), 1,
      sym__newline,
    ACTIONS(47), 1,
      sym__indent,
    STATE(79), 1,
      sym_children,
    ACTIONS(29), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(31), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [889] = 2,
    ACTIONS(198), 5,
      sym__newline,
      sym__indent,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(200), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [905] = 5,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(202), 1,
      anon_sym_elseif,
    ACTIONS(204), 1,
      anon_sym_else,
    STATE(38), 3,
      sym_else_if_statement,
      sym_else_statement,
      aux_sym_conditional_repeat1,
    ACTIONS(140), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [927] = 6,
    ACTIONS(47), 1,
      sym__indent,
    ACTIONS(206), 1,
      sym__space,
    ACTIONS(208), 1,
      sym__newline,
    STATE(91), 1,
      sym_children,
    ACTIONS(130), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(132), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [951] = 5,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(210), 1,
      anon_sym_elseif,
    ACTIONS(213), 1,
      anon_sym_else,
    STATE(38), 3,
      sym_else_if_statement,
      sym_else_statement,
      aux_sym_conditional_repeat1,
    ACTIONS(163), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [973] = 5,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(202), 1,
      anon_sym_elseif,
    ACTIONS(204), 1,
      anon_sym_else,
    STATE(36), 3,
      sym_else_if_statement,
      sym_else_statement,
      aux_sym_conditional_repeat1,
    ACTIONS(159), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [995] = 2,
    ACTIONS(29), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(31), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1010] = 2,
    ACTIONS(185), 5,
      sym__newline,
      sym__indent,
      sym__dedent,
      ts_builtin_sym_end,
      sym__space,
    ACTIONS(187), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1025] = 2,
    ACTIONS(177), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(179), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1040] = 6,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(216), 1,
      sym__space,
    ACTIONS(218), 1,
      sym__newline,
    STATE(104), 1,
      sym_children,
    ACTIONS(132), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1063] = 2,
    ACTIONS(181), 5,
      sym__newline,
      sym__indent,
      sym__dedent,
      ts_builtin_sym_end,
      sym__space,
    ACTIONS(183), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1078] = 2,
    ACTIONS(171), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(173), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1093] = 2,
    ACTIONS(220), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(222), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1108] = 2,
    ACTIONS(224), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(226), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1123] = 5,
    ACTIONS(47), 1,
      sym__indent,
    ACTIONS(208), 1,
      sym__newline,
    STATE(91), 1,
      sym_children,
    ACTIONS(130), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(132), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1144] = 3,
    ACTIONS(232), 1,
      sym__newline,
    ACTIONS(228), 3,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(230), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1161] = 2,
    ACTIONS(130), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(132), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1176] = 4,
    ACTIONS(47), 1,
      sym__indent,
    STATE(79), 1,
      sym_children,
    ACTIONS(29), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(31), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1195] = 2,
    ACTIONS(192), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(194), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1210] = 3,
    ACTIONS(238), 1,
      sym__newline,
    ACTIONS(234), 3,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(236), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1227] = 4,
    ACTIONS(47), 1,
      sym__indent,
    STATE(94), 1,
      sym_children,
    ACTIONS(192), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(194), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1246] = 4,
    ACTIONS(47), 1,
      sym__indent,
    STATE(91), 1,
      sym_children,
    ACTIONS(130), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(132), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1265] = 2,
    ACTIONS(240), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(242), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1280] = 5,
    ACTIONS(47), 1,
      sym__indent,
    ACTIONS(244), 1,
      sym__newline,
    STATE(94), 1,
      sym_children,
    ACTIONS(192), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(194), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1301] = 4,
    ACTIONS(47), 1,
      sym__indent,
    STATE(93), 1,
      sym_children,
    ACTIONS(177), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(179), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1320] = 2,
    ACTIONS(246), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(248), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1335] = 5,
    ACTIONS(47), 1,
      sym__indent,
    ACTIONS(250), 1,
      sym__newline,
    STATE(95), 1,
      sym_children,
    ACTIONS(171), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(173), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1356] = 4,
    ACTIONS(47), 1,
      sym__indent,
    STATE(95), 1,
      sym_children,
    ACTIONS(171), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(173), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1375] = 6,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(120), 1,
      sym__space,
    ACTIONS(122), 1,
      sym__newline,
    STATE(106), 1,
      sym_children,
    ACTIONS(31), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1398] = 2,
    ACTIONS(252), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(254), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1413] = 3,
    ACTIONS(260), 1,
      sym__newline,
    ACTIONS(256), 3,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(258), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1430] = 2,
    ACTIONS(262), 4,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(264), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1445] = 5,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(266), 1,
      sym__newline,
    STATE(100), 1,
      sym_children,
    ACTIONS(173), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1465] = 3,
    ACTIONS(268), 1,
      sym__newline,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(236), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1481] = 5,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    ACTIONS(270), 1,
      sym__newline,
    STATE(108), 1,
      sym_children,
    ACTIONS(194), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1501] = 2,
    ACTIONS(181), 4,
      sym__newline,
      sym__indent,
      ts_builtin_sym_end,
      sym__space,
    ACTIONS(183), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1515] = 2,
    ACTIONS(185), 4,
      sym__newline,
      sym__indent,
      ts_builtin_sym_end,
      sym__space,
    ACTIONS(187), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1529] = 3,
    ACTIONS(272), 1,
      sym__newline,
    ACTIONS(228), 2,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(230), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1545] = 2,
    ACTIONS(262), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(264), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1559] = 3,
    ACTIONS(274), 1,
      sym__newline,
    ACTIONS(256), 2,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(258), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1575] = 2,
    ACTIONS(198), 4,
      sym__newline,
      sym__indent,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(200), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1589] = 5,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(218), 1,
      sym__newline,
    STATE(104), 1,
      sym_children,
    ACTIONS(132), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1609] = 4,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    STATE(108), 1,
      sym_children,
    ACTIONS(194), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1626] = 2,
    ACTIONS(198), 3,
      sym__newline,
      sym__indent,
      ts_builtin_sym_end,
    ACTIONS(200), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1639] = 5,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(124), 1,
      sym_tag_name,
    ACTIONS(276), 1,
      sym__newline,
    STATE(21), 1,
      sym_if_statement,
    STATE(14), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [1658] = 2,
    ACTIONS(130), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(132), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1671] = 5,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(55), 1,
      sym_tag_name,
    ACTIONS(278), 1,
      sym__newline,
    STATE(21), 1,
      sym_if_statement,
    STATE(5), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [1690] = 5,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(55), 1,
      sym_tag_name,
    ACTIONS(280), 1,
      sym__newline,
    STATE(21), 1,
      sym_if_statement,
    STATE(7), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [1709] = 4,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    STATE(104), 1,
      sym_children,
    ACTIONS(132), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1726] = 2,
    ACTIONS(224), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(226), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1739] = 2,
    ACTIONS(29), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(31), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1752] = 2,
    ACTIONS(252), 2,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(254), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1765] = 4,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    STATE(107), 1,
      sym_children,
    ACTIONS(179), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1782] = 2,
    ACTIONS(224), 2,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(226), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1795] = 4,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      sym__indent,
    STATE(106), 1,
      sym_children,
    ACTIONS(31), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1812] = 5,
    ACTIONS(53), 1,
      anon_sym_if,
    ACTIONS(124), 1,
      sym_tag_name,
    ACTIONS(282), 1,
      sym__newline,
    STATE(21), 1,
      sym_if_statement,
    STATE(18), 4,
      sym_tag,
      sym_conditional,
      sym__children_choice,
      aux_sym_children_repeat1,
  [1831] = 2,
    ACTIONS(240), 2,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(242), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1844] = 2,
    ACTIONS(171), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(173), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1857] = 4,
    ACTIONS(116), 1,
      sym__indent,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    STATE(100), 1,
      sym_children,
    ACTIONS(173), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1874] = 2,
    ACTIONS(220), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(222), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1887] = 2,
    ACTIONS(177), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(179), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1900] = 2,
    ACTIONS(192), 3,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(194), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1913] = 2,
    ACTIONS(246), 2,
      ts_builtin_sym_end,
      anon_sym_elseif,
    ACTIONS(248), 6,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      anon_sym_else,
      sym_tag_name,
  [1926] = 3,
    ACTIONS(284), 1,
      ts_builtin_sym_end,
    ACTIONS(288), 1,
      sym__newline,
    ACTIONS(286), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1940] = 2,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
    ACTIONS(226), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1951] = 2,
    ACTIONS(290), 1,
      ts_builtin_sym_end,
    ACTIONS(292), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1962] = 2,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    ACTIONS(194), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1973] = 2,
    ACTIONS(294), 1,
      ts_builtin_sym_end,
    ACTIONS(296), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1984] = 2,
    ACTIONS(298), 1,
      ts_builtin_sym_end,
    ACTIONS(300), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [1995] = 2,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [2006] = 2,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [2017] = 2,
    ACTIONS(302), 1,
      ts_builtin_sym_end,
    ACTIONS(304), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [2028] = 2,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [2039] = 2,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
    ACTIONS(222), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [2050] = 2,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    ACTIONS(179), 5,
      anon_sym_extends,
      anon_sym_include,
      anon_sym_block,
      anon_sym_if,
      sym_tag_name,
  [2061] = 3,
    ACTIONS(306), 1,
      anon_sym_RPAREN,
    ACTIONS(308), 1,
      sym_attribute_name,
    STATE(113), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
  [2072] = 3,
    ACTIONS(308), 1,
      sym_attribute_name,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
    STATE(115), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
  [2083] = 3,
    ACTIONS(308), 1,
      sym_attribute_name,
    ACTIONS(312), 1,
      anon_sym_RPAREN,
    STATE(114), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
  [2094] = 3,
    ACTIONS(308), 1,
      sym_attribute_name,
    ACTIONS(314), 1,
      anon_sym_RPAREN,
    STATE(111), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
  [2105] = 3,
    ACTIONS(308), 1,
      sym_attribute_name,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
    STATE(114), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
  [2116] = 3,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
    ACTIONS(320), 1,
      sym_attribute_name,
    STATE(114), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
  [2127] = 3,
    ACTIONS(308), 1,
      sym_attribute_name,
    ACTIONS(323), 1,
      anon_sym_RPAREN,
    STATE(114), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
  [2138] = 2,
    ACTIONS(325), 1,
      aux_sym_condition_token1,
    STATE(57), 1,
      sym_inline_text,
  [2145] = 2,
    ACTIONS(27), 1,
      sym__indent,
    STATE(59), 1,
      sym_children,
  [2152] = 2,
    ACTIONS(327), 1,
      aux_sym_condition_token1,
    STATE(73), 1,
      sym_condition,
  [2159] = 2,
    ACTIONS(329), 1,
      sym__indent,
    STATE(96), 1,
      sym_children,
  [2166] = 2,
    ACTIONS(331), 1,
      aux_sym_condition_token1,
    STATE(33), 1,
      sym_inline_text,
  [2173] = 2,
    ACTIONS(333), 1,
      aux_sym_condition_token1,
    STATE(66), 1,
      sym_inline_text,
  [2180] = 2,
    ACTIONS(333), 1,
      aux_sym_condition_token1,
    STATE(68), 1,
      sym_inline_text,
  [2187] = 2,
    ACTIONS(329), 1,
      sym__indent,
    STATE(85), 1,
      sym_children,
  [2194] = 2,
    ACTIONS(331), 1,
      aux_sym_condition_token1,
    STATE(23), 1,
      sym_inline_text,
  [2201] = 2,
    ACTIONS(327), 1,
      aux_sym_condition_token1,
    STATE(71), 1,
      sym_condition,
  [2208] = 2,
    ACTIONS(335), 1,
      aux_sym_condition_token1,
    STATE(64), 1,
      sym_condition,
  [2215] = 2,
    ACTIONS(329), 1,
      sym__indent,
    STATE(90), 1,
      sym_children,
  [2222] = 2,
    ACTIONS(335), 1,
      aux_sym_condition_token1,
    STATE(49), 1,
      sym_condition,
  [2229] = 2,
    ACTIONS(325), 1,
      aux_sym_condition_token1,
    STATE(60), 1,
      sym_inline_text,
  [2236] = 1,
    ACTIONS(337), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [2241] = 2,
    ACTIONS(325), 1,
      aux_sym_condition_token1,
    STATE(48), 1,
      sym_inline_text,
  [2248] = 2,
    ACTIONS(27), 1,
      sym__indent,
    STATE(63), 1,
      sym_children,
  [2255] = 2,
    ACTIONS(331), 1,
      aux_sym_condition_token1,
    STATE(27), 1,
      sym_inline_text,
  [2262] = 1,
    ACTIONS(339), 2,
      sym_quoted_attribute_value,
      sym_unquoted_attribute_value,
  [2267] = 2,
    ACTIONS(333), 1,
      aux_sym_condition_token1,
    STATE(75), 1,
      sym_inline_text,
  [2274] = 2,
    ACTIONS(27), 1,
      sym__indent,
    STATE(56), 1,
      sym_children,
  [2281] = 2,
    ACTIONS(116), 1,
      sym__indent,
    STATE(101), 1,
      sym_children,
  [2288] = 1,
    ACTIONS(341), 1,
      sym_identifier,
  [2292] = 1,
    ACTIONS(343), 1,
      sym_identifier,
  [2296] = 1,
    ACTIONS(345), 1,
      sym_identifier,
  [2300] = 1,
    ACTIONS(347), 1,
      anon_sym_EQ,
  [2304] = 1,
    ACTIONS(349), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 174,
  [SMALL_STATE(8)] = 206,
  [SMALL_STATE(9)] = 242,
  [SMALL_STATE(10)] = 266,
  [SMALL_STATE(11)] = 299,
  [SMALL_STATE(12)] = 332,
  [SMALL_STATE(13)] = 367,
  [SMALL_STATE(14)] = 402,
  [SMALL_STATE(15)] = 432,
  [SMALL_STATE(16)] = 458,
  [SMALL_STATE(17)] = 482,
  [SMALL_STATE(18)] = 504,
  [SMALL_STATE(19)] = 534,
  [SMALL_STATE(20)] = 560,
  [SMALL_STATE(21)] = 588,
  [SMALL_STATE(22)] = 612,
  [SMALL_STATE(23)] = 636,
  [SMALL_STATE(24)] = 659,
  [SMALL_STATE(25)] = 680,
  [SMALL_STATE(26)] = 701,
  [SMALL_STATE(27)] = 718,
  [SMALL_STATE(28)] = 741,
  [SMALL_STATE(29)] = 762,
  [SMALL_STATE(30)] = 779,
  [SMALL_STATE(31)] = 800,
  [SMALL_STATE(32)] = 821,
  [SMALL_STATE(33)] = 842,
  [SMALL_STATE(34)] = 865,
  [SMALL_STATE(35)] = 889,
  [SMALL_STATE(36)] = 905,
  [SMALL_STATE(37)] = 927,
  [SMALL_STATE(38)] = 951,
  [SMALL_STATE(39)] = 973,
  [SMALL_STATE(40)] = 995,
  [SMALL_STATE(41)] = 1010,
  [SMALL_STATE(42)] = 1025,
  [SMALL_STATE(43)] = 1040,
  [SMALL_STATE(44)] = 1063,
  [SMALL_STATE(45)] = 1078,
  [SMALL_STATE(46)] = 1093,
  [SMALL_STATE(47)] = 1108,
  [SMALL_STATE(48)] = 1123,
  [SMALL_STATE(49)] = 1144,
  [SMALL_STATE(50)] = 1161,
  [SMALL_STATE(51)] = 1176,
  [SMALL_STATE(52)] = 1195,
  [SMALL_STATE(53)] = 1210,
  [SMALL_STATE(54)] = 1227,
  [SMALL_STATE(55)] = 1246,
  [SMALL_STATE(56)] = 1265,
  [SMALL_STATE(57)] = 1280,
  [SMALL_STATE(58)] = 1301,
  [SMALL_STATE(59)] = 1320,
  [SMALL_STATE(60)] = 1335,
  [SMALL_STATE(61)] = 1356,
  [SMALL_STATE(62)] = 1375,
  [SMALL_STATE(63)] = 1398,
  [SMALL_STATE(64)] = 1413,
  [SMALL_STATE(65)] = 1430,
  [SMALL_STATE(66)] = 1445,
  [SMALL_STATE(67)] = 1465,
  [SMALL_STATE(68)] = 1481,
  [SMALL_STATE(69)] = 1501,
  [SMALL_STATE(70)] = 1515,
  [SMALL_STATE(71)] = 1529,
  [SMALL_STATE(72)] = 1545,
  [SMALL_STATE(73)] = 1559,
  [SMALL_STATE(74)] = 1575,
  [SMALL_STATE(75)] = 1589,
  [SMALL_STATE(76)] = 1609,
  [SMALL_STATE(77)] = 1626,
  [SMALL_STATE(78)] = 1639,
  [SMALL_STATE(79)] = 1658,
  [SMALL_STATE(80)] = 1671,
  [SMALL_STATE(81)] = 1690,
  [SMALL_STATE(82)] = 1709,
  [SMALL_STATE(83)] = 1726,
  [SMALL_STATE(84)] = 1739,
  [SMALL_STATE(85)] = 1752,
  [SMALL_STATE(86)] = 1765,
  [SMALL_STATE(87)] = 1782,
  [SMALL_STATE(88)] = 1795,
  [SMALL_STATE(89)] = 1812,
  [SMALL_STATE(90)] = 1831,
  [SMALL_STATE(91)] = 1844,
  [SMALL_STATE(92)] = 1857,
  [SMALL_STATE(93)] = 1874,
  [SMALL_STATE(94)] = 1887,
  [SMALL_STATE(95)] = 1900,
  [SMALL_STATE(96)] = 1913,
  [SMALL_STATE(97)] = 1926,
  [SMALL_STATE(98)] = 1940,
  [SMALL_STATE(99)] = 1951,
  [SMALL_STATE(100)] = 1962,
  [SMALL_STATE(101)] = 1973,
  [SMALL_STATE(102)] = 1984,
  [SMALL_STATE(103)] = 1995,
  [SMALL_STATE(104)] = 2006,
  [SMALL_STATE(105)] = 2017,
  [SMALL_STATE(106)] = 2028,
  [SMALL_STATE(107)] = 2039,
  [SMALL_STATE(108)] = 2050,
  [SMALL_STATE(109)] = 2061,
  [SMALL_STATE(110)] = 2072,
  [SMALL_STATE(111)] = 2083,
  [SMALL_STATE(112)] = 2094,
  [SMALL_STATE(113)] = 2105,
  [SMALL_STATE(114)] = 2116,
  [SMALL_STATE(115)] = 2127,
  [SMALL_STATE(116)] = 2138,
  [SMALL_STATE(117)] = 2145,
  [SMALL_STATE(118)] = 2152,
  [SMALL_STATE(119)] = 2159,
  [SMALL_STATE(120)] = 2166,
  [SMALL_STATE(121)] = 2173,
  [SMALL_STATE(122)] = 2180,
  [SMALL_STATE(123)] = 2187,
  [SMALL_STATE(124)] = 2194,
  [SMALL_STATE(125)] = 2201,
  [SMALL_STATE(126)] = 2208,
  [SMALL_STATE(127)] = 2215,
  [SMALL_STATE(128)] = 2222,
  [SMALL_STATE(129)] = 2229,
  [SMALL_STATE(130)] = 2236,
  [SMALL_STATE(131)] = 2241,
  [SMALL_STATE(132)] = 2248,
  [SMALL_STATE(133)] = 2255,
  [SMALL_STATE(134)] = 2262,
  [SMALL_STATE(135)] = 2267,
  [SMALL_STATE(136)] = 2274,
  [SMALL_STATE(137)] = 2281,
  [SMALL_STATE(138)] = 2288,
  [SMALL_STATE(139)] = 2292,
  [SMALL_STATE(140)] = 2296,
  [SMALL_STATE(141)] = 2300,
  [SMALL_STATE(142)] = 2304,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(139),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 1),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 2),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_children, 2),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_children_repeat1, 2),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_children_repeat1, 2),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_children_repeat1, 2), SHIFT_REPEAT(128),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_children_repeat1, 2), SHIFT_REPEAT(2),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_children_repeat1, 2), SHIFT_REPEAT(6),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(9),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(139),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(138),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(140),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(125),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(12),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 2),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(17),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_children_repeat1, 2), SHIFT_REPEAT(8),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_children_repeat1, 2), SHIFT_REPEAT(20),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 1),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conditional_repeat1, 2),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_conditional_repeat1, 2),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conditional_repeat1, 2), SHIFT_REPEAT(126),
  [168] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_conditional_repeat1, 2), SHIFT_REPEAT(53),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 3),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 3),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(31),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_text, 1),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_text, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conditional_repeat1, 2), SHIFT_REPEAT(118),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_conditional_repeat1, 2), SHIFT_REPEAT(67),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 7),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 7),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_children, 3),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_children, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 2),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 2),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_statement, 1),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_statement, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_if_statement, 4),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_if_statement, 4),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_statement, 3),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_statement, 3),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_if_statement, 2),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_if_statement, 2),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 1),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 2),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 2),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_expansion, 1),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_expansion, 1),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 4),
  [296] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 4),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_statement, 2),
  [300] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extends_statement, 2),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_statement, 2),
  [304] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_statement, 2),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2),
  [320] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2), SHIFT_REPEAT(141),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [339] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [349] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
  },
  [5] = {
    [ts_external_token__indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_pug_external_scanner_create(void);
void tree_sitter_pug_external_scanner_destroy(void *);
bool tree_sitter_pug_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_pug_external_scanner_serialize(void *, char *);
void tree_sitter_pug_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_pug(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_pug_external_scanner_create,
      tree_sitter_pug_external_scanner_destroy,
      tree_sitter_pug_external_scanner_scan,
      tree_sitter_pug_external_scanner_serialize,
      tree_sitter_pug_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
