#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 129
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 10

enum ts_symbol_identifiers {
  aux_sym_tag_name_token1 = 1,
  anon_sym_DOT = 2,
  anon_sym_POUND = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_EQ = 7,
  aux_sym_string_token1 = 8,
  aux_sym_string_token2 = 9,
  sym_expression = 10,
  anon_sym_SPACE = 11,
  aux_sym_inline_text_token1 = 12,
  anon_sym_PIPE = 13,
  anon_sym_DASH = 14,
  anon_sym_mixin = 15,
  anon_sym_if = 16,
  anon_sym_elseif = 17,
  anon_sym_else = 18,
  anon_sym_each = 19,
  anon_sym_doctype = 20,
  sym_comment = 21,
  sym__newline = 22,
  sym__indent = 23,
  sym__dedent = 24,
  sym_source_file = 25,
  sym__block = 26,
  sym_tag = 27,
  sym_tag_name = 28,
  sym_class_or_id = 29,
  sym_attributes = 30,
  sym_attribute = 31,
  sym_attribute_name = 32,
  sym_attribute_value = 33,
  sym_string = 34,
  sym_inline_text = 35,
  sym_indented_block = 36,
  sym_text = 37,
  sym_code_block = 38,
  sym_mixin = 39,
  sym_conditional = 40,
  sym_loop = 41,
  sym_doctype = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_tag_repeat1 = 44,
  aux_sym_attributes_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_tag_name_token1] = "tag_name_token1",
  [anon_sym_DOT] = ".",
  [anon_sym_POUND] = "#",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_expression] = "expression",
  [anon_sym_SPACE] = " ",
  [aux_sym_inline_text_token1] = "inline_text_token1",
  [anon_sym_PIPE] = "|",
  [anon_sym_DASH] = "-",
  [anon_sym_mixin] = "mixin",
  [anon_sym_if] = "if",
  [anon_sym_elseif] = "else if",
  [anon_sym_else] = "else",
  [anon_sym_each] = "each",
  [anon_sym_doctype] = "doctype",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_source_file] = "source_file",
  [sym__block] = "_block",
  [sym_tag] = "tag",
  [sym_tag_name] = "tag_name",
  [sym_class_or_id] = "class_or_id",
  [sym_attributes] = "attributes",
  [sym_attribute] = "attribute",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_string] = "string",
  [sym_inline_text] = "inline_text",
  [sym_indented_block] = "indented_block",
  [sym_text] = "text",
  [sym_code_block] = "code_block",
  [sym_mixin] = "mixin",
  [sym_conditional] = "conditional",
  [sym_loop] = "loop",
  [sym_doctype] = "doctype",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym_attributes_repeat1] = "attributes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_tag_name_token1] = aux_sym_tag_name_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_expression] = sym_expression,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym_inline_text_token1] = aux_sym_inline_text_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_mixin] = anon_sym_mixin,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_doctype] = anon_sym_doctype,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_source_file] = sym_source_file,
  [sym__block] = sym__block,
  [sym_tag] = sym_tag,
  [sym_tag_name] = sym_tag_name,
  [sym_class_or_id] = sym_class_or_id,
  [sym_attributes] = sym_attributes,
  [sym_attribute] = sym_attribute,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_string] = sym_string,
  [sym_inline_text] = sym_inline_text,
  [sym_indented_block] = sym_indented_block,
  [sym_text] = sym_text,
  [sym_code_block] = sym_code_block,
  [sym_mixin] = sym_mixin,
  [sym_conditional] = sym_conditional,
  [sym_loop] = sym_loop,
  [sym_doctype] = sym_doctype,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym_attributes_repeat1] = aux_sym_attributes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_tag_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_inline_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mixin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_doctype] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class_or_id] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_text] = {
    .visible = true,
    .named = true,
  },
  [sym_indented_block] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_mixin] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block = 1,
  field_inline_text = 2,
  field_name = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block] = "block",
  [field_inline_text] = "inline_text",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 3},
  [9] = {.index = 16, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_inline_text, 1},
    {field_name, 0},
  [3] =
    {field_block, 1},
    {field_name, 0},
  [5] =
    {field_name, 2},
  [6] =
    {field_block, 2},
    {field_inline_text, 1},
    {field_name, 0},
  [9] =
    {field_inline_text, 2},
    {field_name, 0},
  [11] =
    {field_block, 2},
    {field_name, 0},
  [13] =
    {field_block, 3},
    {field_inline_text, 2},
    {field_name, 0},
  [16] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 4,
  [8] = 8,
  [9] = 3,
  [10] = 6,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
  [21] = 15,
  [22] = 18,
  [23] = 19,
  [24] = 16,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 27,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 17,
  [36] = 31,
  [37] = 32,
  [38] = 34,
  [39] = 33,
  [40] = 40,
  [41] = 17,
  [42] = 42,
  [43] = 42,
  [44] = 40,
  [45] = 45,
  [46] = 45,
  [47] = 47,
  [48] = 19,
  [49] = 18,
  [50] = 16,
  [51] = 19,
  [52] = 47,
  [53] = 18,
  [54] = 16,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 58,
  [64] = 61,
  [65] = 65,
  [66] = 60,
  [67] = 59,
  [68] = 68,
  [69] = 69,
  [70] = 65,
  [71] = 71,
  [72] = 68,
  [73] = 55,
  [74] = 74,
  [75] = 56,
  [76] = 62,
  [77] = 57,
  [78] = 69,
  [79] = 71,
  [80] = 80,
  [81] = 74,
  [82] = 80,
  [83] = 83,
  [84] = 84,
  [85] = 84,
  [86] = 84,
  [87] = 84,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 88,
  [92] = 89,
  [93] = 88,
  [94] = 94,
  [95] = 95,
  [96] = 89,
  [97] = 88,
  [98] = 98,
  [99] = 89,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 100,
  [106] = 106,
  [107] = 107,
  [108] = 106,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 109,
  [116] = 116,
  [117] = 110,
  [118] = 111,
  [119] = 112,
  [120] = 114,
  [121] = 107,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 116,
  [126] = 123,
  [127] = 124,
  [128] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(34);
      if (lookahead == 'd') ADVANCE(22);
      if (lookahead == 'e') ADVANCE(12);
      if (lookahead == 'i') ADVANCE(17);
      if (lookahead == 'm') ADVANCE(19);
      if (lookahead == '|') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\'') ADVANCE(41);
      if (lookahead == '/') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2)
      if (lookahead == '/') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3)
      if (lookahead == '/') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(60);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(56);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == ' ') ADVANCE(47);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == 'd') ADVANCE(22);
      if (lookahead == 'e') ADVANCE(12);
      if (lookahead == 'i') ADVANCE(17);
      if (lookahead == 'm') ADVANCE(19);
      if (lookahead == '|') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(10)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'c') ADVANCE(18);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'f') ADVANCE(55);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'h') ADVANCE(58);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'i') ADVANCE(26);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'i') ADVANCE(21);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'n') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'o') ADVANCE(13);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'p') ADVANCE(16);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 's') ADVANCE(15);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 't') ADVANCE(27);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'x') ADVANCE(20);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == 'y') ADVANCE(23);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\'') ADVANCE(41);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == '"') ADVANCE(36);
      if (lookahead == '\n' ||
          lookahead == ')') ADVANCE(4);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == '\'') ADVANCE(38);
      if (lookahead == '\n' ||
          lookahead == ')') ADVANCE(5);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == ')') ADVANCE(61);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == ')') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_inline_text_token1);
      if (lookahead == '-') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_inline_text_token1);
      if (lookahead == '/') ADVANCE(50);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_inline_text_token1);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_inline_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_mixin);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_each);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_doctype);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '-') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 10, .external_lex_state = 3},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 10, .external_lex_state = 4},
  [7] = {.lex_state = 10, .external_lex_state = 4},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 10, .external_lex_state = 3},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 10, .external_lex_state = 3},
  [14] = {.lex_state = 10, .external_lex_state = 4},
  [15] = {.lex_state = 10, .external_lex_state = 3},
  [16] = {.lex_state = 10, .external_lex_state = 4},
  [17] = {.lex_state = 10, .external_lex_state = 4},
  [18] = {.lex_state = 10, .external_lex_state = 4},
  [19] = {.lex_state = 10, .external_lex_state = 4},
  [20] = {.lex_state = 10, .external_lex_state = 3},
  [21] = {.lex_state = 10, .external_lex_state = 4},
  [22] = {.lex_state = 10, .external_lex_state = 3},
  [23] = {.lex_state = 10, .external_lex_state = 3},
  [24] = {.lex_state = 10, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 4},
  [27] = {.lex_state = 10, .external_lex_state = 3},
  [28] = {.lex_state = 10, .external_lex_state = 4},
  [29] = {.lex_state = 10, .external_lex_state = 3},
  [30] = {.lex_state = 10, .external_lex_state = 4},
  [31] = {.lex_state = 0, .external_lex_state = 4},
  [32] = {.lex_state = 0, .external_lex_state = 4},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 3},
  [36] = {.lex_state = 0, .external_lex_state = 3},
  [37] = {.lex_state = 0, .external_lex_state = 3},
  [38] = {.lex_state = 0, .external_lex_state = 3},
  [39] = {.lex_state = 0, .external_lex_state = 3},
  [40] = {.lex_state = 0, .external_lex_state = 4},
  [41] = {.lex_state = 0, .external_lex_state = 4},
  [42] = {.lex_state = 0, .external_lex_state = 4},
  [43] = {.lex_state = 0, .external_lex_state = 3},
  [44] = {.lex_state = 0, .external_lex_state = 3},
  [45] = {.lex_state = 10, .external_lex_state = 2},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 0, .external_lex_state = 4},
  [48] = {.lex_state = 0, .external_lex_state = 3},
  [49] = {.lex_state = 0, .external_lex_state = 3},
  [50] = {.lex_state = 0, .external_lex_state = 4},
  [51] = {.lex_state = 0, .external_lex_state = 4},
  [52] = {.lex_state = 0, .external_lex_state = 3},
  [53] = {.lex_state = 0, .external_lex_state = 4},
  [54] = {.lex_state = 0, .external_lex_state = 3},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 0, .external_lex_state = 2},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 2},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 6},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 6},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 6},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 6},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 6},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 3},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 6},
  [113] = {.lex_state = 0, .external_lex_state = 5},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 3},
  [116] = {.lex_state = 10},
  [117] = {.lex_state = 3},
  [118] = {.lex_state = 2},
  [119] = {.lex_state = 6},
  [120] = {.lex_state = 2},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 10},
  [124] = {.lex_state = 10},
  [125] = {.lex_state = 10},
  [126] = {.lex_state = 10},
  [127] = {.lex_state = 10},
  [128] = {.lex_state = 0, .external_lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_tag_name_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_mixin] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_doctype] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(122),
    [sym__block] = STATE(8),
    [sym_tag] = STATE(8),
    [sym_tag_name] = STATE(7),
    [sym_text] = STATE(8),
    [sym_code_block] = STATE(8),
    [sym_mixin] = STATE(8),
    [sym_conditional] = STATE(8),
    [sym_loop] = STATE(8),
    [sym_doctype] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_tag_name_token1] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_mixin] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_elseif] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(15),
    [anon_sym_each] = ACTIONS(19),
    [anon_sym_doctype] = ACTIONS(21),
    [sym_comment] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(25), 1,
      aux_sym_tag_name_token1,
    ACTIONS(28), 1,
      anon_sym_PIPE,
    ACTIONS(31), 1,
      anon_sym_DASH,
    ACTIONS(34), 1,
      anon_sym_mixin,
    ACTIONS(40), 1,
      anon_sym_elseif,
    ACTIONS(43), 1,
      anon_sym_each,
    ACTIONS(46), 1,
      anon_sym_doctype,
    ACTIONS(49), 1,
      sym_comment,
    ACTIONS(52), 1,
      sym__dedent,
    STATE(4), 1,
      sym_tag_name,
    ACTIONS(37), 2,
      anon_sym_if,
      anon_sym_else,
    STATE(2), 9,
      sym__block,
      sym_tag,
      sym_text,
      sym_code_block,
      sym_mixin,
      sym_conditional,
      sym_loop,
      sym_doctype,
      aux_sym_source_file_repeat1,
  [46] = 12,
    ACTIONS(54), 1,
      aux_sym_tag_name_token1,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(60), 1,
      anon_sym_mixin,
    ACTIONS(64), 1,
      anon_sym_elseif,
    ACTIONS(66), 1,
      anon_sym_each,
    ACTIONS(68), 1,
      anon_sym_doctype,
    ACTIONS(70), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym__dedent,
    STATE(4), 1,
      sym_tag_name,
    ACTIONS(62), 2,
      anon_sym_if,
      anon_sym_else,
    STATE(2), 9,
      sym__block,
      sym_tag,
      sym_text,
      sym_code_block,
      sym_mixin,
      sym_conditional,
      sym_loop,
      sym_doctype,
      aux_sym_source_file_repeat1,
  [92] = 9,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_SPACE,
    ACTIONS(82), 1,
      sym__newline,
    ACTIONS(84), 1,
      sym__dedent,
    STATE(36), 1,
      sym_inline_text,
    STATE(55), 1,
      sym_indented_block,
    ACTIONS(76), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(10), 3,
      sym_class_or_id,
      sym_attributes,
      aux_sym_tag_repeat1,
    ACTIONS(74), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [132] = 12,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      aux_sym_tag_name_token1,
    ACTIONS(89), 1,
      anon_sym_PIPE,
    ACTIONS(92), 1,
      anon_sym_DASH,
    ACTIONS(95), 1,
      anon_sym_mixin,
    ACTIONS(101), 1,
      anon_sym_elseif,
    ACTIONS(104), 1,
      anon_sym_each,
    ACTIONS(107), 1,
      anon_sym_doctype,
    ACTIONS(110), 1,
      sym_comment,
    STATE(7), 1,
      sym_tag_name,
    ACTIONS(98), 2,
      anon_sym_if,
      anon_sym_else,
    STATE(5), 9,
      sym__block,
      sym_tag,
      sym_text,
      sym_code_block,
      sym_mixin,
      sym_conditional,
      sym_loop,
      sym_doctype,
      aux_sym_source_file_repeat1,
  [178] = 9,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_SPACE,
    ACTIONS(123), 1,
      sym__newline,
    STATE(42), 1,
      sym_inline_text,
    STATE(57), 1,
      sym_indented_block,
    ACTIONS(117), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(14), 3,
      sym_class_or_id,
      sym_attributes,
      aux_sym_tag_repeat1,
    ACTIONS(115), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [218] = 9,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(119), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_SPACE,
    ACTIONS(123), 1,
      sym__newline,
    STATE(31), 1,
      sym_inline_text,
    STATE(73), 1,
      sym_indented_block,
    ACTIONS(117), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(6), 3,
      sym_class_or_id,
      sym_attributes,
      aux_sym_tag_repeat1,
    ACTIONS(74), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [258] = 12,
    ACTIONS(7), 1,
      aux_sym_tag_name_token1,
    ACTIONS(9), 1,
      anon_sym_PIPE,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_mixin,
    ACTIONS(17), 1,
      anon_sym_elseif,
    ACTIONS(19), 1,
      anon_sym_each,
    ACTIONS(21), 1,
      anon_sym_doctype,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 1,
      sym_comment,
    STATE(7), 1,
      sym_tag_name,
    ACTIONS(15), 2,
      anon_sym_if,
      anon_sym_else,
    STATE(5), 9,
      sym__block,
      sym_tag,
      sym_text,
      sym_code_block,
      sym_mixin,
      sym_conditional,
      sym_loop,
      sym_doctype,
      aux_sym_source_file_repeat1,
  [304] = 12,
    ACTIONS(54), 1,
      aux_sym_tag_name_token1,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(60), 1,
      anon_sym_mixin,
    ACTIONS(64), 1,
      anon_sym_elseif,
    ACTIONS(66), 1,
      anon_sym_each,
    ACTIONS(68), 1,
      anon_sym_doctype,
    ACTIONS(70), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym__dedent,
    STATE(4), 1,
      sym_tag_name,
    ACTIONS(62), 2,
      anon_sym_if,
      anon_sym_else,
    STATE(2), 9,
      sym__block,
      sym_tag,
      sym_text,
      sym_code_block,
      sym_mixin,
      sym_conditional,
      sym_loop,
      sym_doctype,
      aux_sym_source_file_repeat1,
  [350] = 9,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_SPACE,
    ACTIONS(82), 1,
      sym__newline,
    ACTIONS(113), 1,
      sym__dedent,
    STATE(43), 1,
      sym_inline_text,
    STATE(77), 1,
      sym_indented_block,
    ACTIONS(76), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(13), 3,
      sym_class_or_id,
      sym_attributes,
      aux_sym_tag_repeat1,
    ACTIONS(115), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [390] = 11,
    ACTIONS(54), 1,
      aux_sym_tag_name_token1,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(60), 1,
      anon_sym_mixin,
    ACTIONS(64), 1,
      anon_sym_elseif,
    ACTIONS(66), 1,
      anon_sym_each,
    ACTIONS(68), 1,
      anon_sym_doctype,
    ACTIONS(131), 1,
      sym_comment,
    STATE(4), 1,
      sym_tag_name,
    ACTIONS(62), 2,
      anon_sym_if,
      anon_sym_else,
    STATE(9), 9,
      sym__block,
      sym_tag,
      sym_text,
      sym_code_block,
      sym_mixin,
      sym_conditional,
      sym_loop,
      sym_doctype,
      aux_sym_source_file_repeat1,
  [433] = 11,
    ACTIONS(54), 1,
      aux_sym_tag_name_token1,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(60), 1,
      anon_sym_mixin,
    ACTIONS(64), 1,
      anon_sym_elseif,
    ACTIONS(66), 1,
      anon_sym_each,
    ACTIONS(68), 1,
      anon_sym_doctype,
    ACTIONS(133), 1,
      sym_comment,
    STATE(4), 1,
      sym_tag_name,
    ACTIONS(62), 2,
      anon_sym_if,
      anon_sym_else,
    STATE(3), 9,
      sym__block,
      sym_tag,
      sym_text,
      sym_code_block,
      sym_mixin,
      sym_conditional,
      sym_loop,
      sym_doctype,
      aux_sym_source_file_repeat1,
  [476] = 5,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
    ACTIONS(137), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(143), 3,
      sym__newline,
      sym__dedent,
      anon_sym_SPACE,
    STATE(13), 3,
      sym_class_or_id,
      sym_attributes,
      aux_sym_tag_repeat1,
    ACTIONS(135), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [506] = 5,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(143), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    STATE(14), 3,
      sym_class_or_id,
      sym_attributes,
      aux_sym_tag_repeat1,
    ACTIONS(135), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [536] = 2,
    ACTIONS(153), 3,
      sym__newline,
      sym__dedent,
      anon_sym_SPACE,
    ACTIONS(151), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [557] = 2,
    ACTIONS(155), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(157), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [578] = 2,
    ACTIONS(159), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(161), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [599] = 2,
    ACTIONS(163), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(165), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [620] = 2,
    ACTIONS(167), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(169), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [641] = 2,
    ACTIONS(159), 3,
      sym__newline,
      sym__dedent,
      anon_sym_SPACE,
    ACTIONS(161), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [662] = 2,
    ACTIONS(153), 3,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_SPACE,
    ACTIONS(151), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [683] = 2,
    ACTIONS(163), 3,
      sym__newline,
      sym__dedent,
      anon_sym_SPACE,
    ACTIONS(165), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [704] = 2,
    ACTIONS(167), 3,
      sym__newline,
      sym__dedent,
      anon_sym_SPACE,
    ACTIONS(169), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [725] = 2,
    ACTIONS(155), 3,
      sym__newline,
      sym__dedent,
      anon_sym_SPACE,
    ACTIONS(157), 13,
      aux_sym_tag_name_token1,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [746] = 6,
    ACTIONS(82), 1,
      sym__newline,
    ACTIONS(173), 1,
      anon_sym_LPAREN,
    STATE(44), 1,
      sym_attributes,
    STATE(58), 1,
      sym_indented_block,
    ACTIONS(175), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(171), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [774] = 6,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(177), 1,
      anon_sym_LPAREN,
    STATE(40), 1,
      sym_attributes,
    STATE(63), 1,
      sym_indented_block,
    ACTIONS(175), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(171), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [802] = 5,
    ACTIONS(82), 1,
      sym__newline,
    ACTIONS(181), 1,
      anon_sym_SPACE,
    ACTIONS(183), 1,
      sym__dedent,
    STATE(71), 1,
      sym_indented_block,
    ACTIONS(179), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [827] = 5,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    ACTIONS(189), 1,
      anon_sym_SPACE,
    STATE(65), 1,
      sym_indented_block,
    ACTIONS(187), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [852] = 5,
    ACTIONS(82), 1,
      sym__newline,
    ACTIONS(185), 1,
      sym__dedent,
    ACTIONS(191), 1,
      anon_sym_SPACE,
    STATE(70), 1,
      sym_indented_block,
    ACTIONS(187), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [877] = 5,
    ACTIONS(123), 1,
      sym__newline,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
    ACTIONS(193), 1,
      anon_sym_SPACE,
    STATE(79), 1,
      sym_indented_block,
    ACTIONS(179), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [902] = 4,
    ACTIONS(123), 1,
      sym__newline,
    STATE(80), 1,
      sym_indented_block,
    ACTIONS(195), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(197), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [924] = 4,
    ACTIONS(123), 1,
      sym__newline,
    STATE(68), 1,
      sym_indented_block,
    ACTIONS(199), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(201), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [946] = 4,
    ACTIONS(123), 1,
      sym__newline,
    STATE(81), 1,
      sym_indented_block,
    ACTIONS(203), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(205), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [968] = 4,
    ACTIONS(123), 1,
      sym__newline,
    STATE(62), 1,
      sym_indented_block,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(209), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [990] = 2,
    ACTIONS(161), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
    ACTIONS(159), 7,
      sym__newline,
      sym__dedent,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
  [1008] = 4,
    ACTIONS(82), 1,
      sym__newline,
    STATE(82), 1,
      sym_indented_block,
    ACTIONS(195), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(197), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1030] = 4,
    ACTIONS(82), 1,
      sym__newline,
    STATE(72), 1,
      sym_indented_block,
    ACTIONS(199), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(201), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1052] = 4,
    ACTIONS(82), 1,
      sym__newline,
    STATE(76), 1,
      sym_indented_block,
    ACTIONS(207), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(209), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1074] = 4,
    ACTIONS(82), 1,
      sym__newline,
    STATE(74), 1,
      sym_indented_block,
    ACTIONS(203), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(205), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1096] = 4,
    ACTIONS(123), 1,
      sym__newline,
    STATE(61), 1,
      sym_indented_block,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(213), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1118] = 2,
    ACTIONS(161), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
    ACTIONS(159), 7,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
  [1136] = 4,
    ACTIONS(123), 1,
      sym__newline,
    STATE(59), 1,
      sym_indented_block,
    ACTIONS(215), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(217), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1158] = 4,
    ACTIONS(82), 1,
      sym__newline,
    STATE(67), 1,
      sym_indented_block,
    ACTIONS(215), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(217), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1180] = 4,
    ACTIONS(82), 1,
      sym__newline,
    STATE(64), 1,
      sym_indented_block,
    ACTIONS(211), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(213), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1202] = 3,
    ACTIONS(221), 1,
      anon_sym_SPACE,
    ACTIONS(223), 1,
      sym__dedent,
    ACTIONS(219), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [1221] = 3,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(225), 1,
      anon_sym_SPACE,
    ACTIONS(219), 10,
      aux_sym_tag_name_token1,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
      sym_comment,
  [1240] = 2,
    ACTIONS(227), 6,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(229), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1257] = 2,
    ACTIONS(167), 6,
      sym__newline,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(169), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1274] = 2,
    ACTIONS(163), 6,
      sym__newline,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(165), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1291] = 2,
    ACTIONS(155), 6,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(157), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1308] = 2,
    ACTIONS(167), 6,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(169), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1325] = 2,
    ACTIONS(227), 6,
      sym__newline,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(229), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1342] = 2,
    ACTIONS(163), 6,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(165), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1359] = 2,
    ACTIONS(155), 6,
      sym__newline,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(157), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1376] = 2,
    ACTIONS(233), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(231), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1392] = 2,
    ACTIONS(235), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(237), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1408] = 2,
    ACTIONS(239), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(241), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1424] = 2,
    ACTIONS(211), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(213), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1440] = 2,
    ACTIONS(243), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(245), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1456] = 2,
    ACTIONS(247), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(249), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1472] = 2,
    ACTIONS(251), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(253), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1488] = 2,
    ACTIONS(255), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(257), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1504] = 2,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(213), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1520] = 2,
    ACTIONS(251), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(253), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1536] = 2,
    ACTIONS(259), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(261), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1552] = 2,
    ACTIONS(247), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(249), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1568] = 2,
    ACTIONS(243), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(245), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1584] = 2,
    ACTIONS(263), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(265), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1600] = 2,
    ACTIONS(267), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(269), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1616] = 2,
    ACTIONS(259), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(261), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1632] = 2,
    ACTIONS(273), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(271), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1648] = 2,
    ACTIONS(263), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(265), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1664] = 2,
    ACTIONS(233), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(231), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1680] = 2,
    ACTIONS(277), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(275), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1696] = 2,
    ACTIONS(235), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(237), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1712] = 2,
    ACTIONS(255), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(257), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1728] = 2,
    ACTIONS(239), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(241), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1744] = 2,
    ACTIONS(267), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(269), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1760] = 2,
    ACTIONS(273), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(271), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1776] = 2,
    ACTIONS(279), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(281), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1792] = 2,
    ACTIONS(277), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(275), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1808] = 2,
    ACTIONS(279), 5,
      sym__dedent,
      anon_sym_PIPE,
      anon_sym_DASH,
      anon_sym_elseif,
      sym_comment,
    ACTIONS(281), 6,
      aux_sym_tag_name_token1,
      anon_sym_mixin,
      anon_sym_if,
      anon_sym_else,
      anon_sym_each,
      anon_sym_doctype,
  [1824] = 5,
    ACTIONS(285), 1,
      sym_expression,
    ACTIONS(287), 1,
      sym_comment,
    STATE(101), 1,
      sym_string,
    STATE(103), 1,
      sym_attribute_value,
    ACTIONS(283), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
  [1841] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      aux_sym_tag_name_token1,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_attribute_name,
    STATE(91), 1,
      sym_attribute,
  [1857] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      aux_sym_tag_name_token1,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_attribute_name,
    STATE(93), 1,
      sym_attribute,
  [1873] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      aux_sym_tag_name_token1,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      sym_attribute,
    STATE(90), 1,
      sym_attribute_name,
  [1889] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      aux_sym_tag_name_token1,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_attribute_name,
    STATE(97), 1,
      sym_attribute,
  [1905] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      aux_sym_attributes_repeat1,
  [1918] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_attributes_repeat1,
  [1931] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_EQ,
    ACTIONS(305), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1942] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_attributes_repeat1,
  [1955] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_attributes_repeat1,
  [1968] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(313), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_attributes_repeat1,
  [1981] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1990] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      aux_sym_tag_name_token1,
    STATE(90), 1,
      sym_attribute_name,
    STATE(104), 1,
      sym_attribute,
  [2003] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(317), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_attributes_repeat1,
  [2016] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
    STATE(99), 1,
      aux_sym_attributes_repeat1,
  [2029] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_COMMA,
    ACTIONS(324), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_attributes_repeat1,
  [2042] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(326), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_attributes_repeat1,
  [2055] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      aux_sym_tag_name_token1,
    STATE(26), 1,
      sym_tag_name,
  [2065] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2073] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2089] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2097] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      aux_sym_tag_name_token1,
    STATE(25), 1,
      sym_tag_name,
  [2107] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(338), 1,
      aux_sym_inline_text_token1,
  [2114] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(340), 1,
      aux_sym_inline_text_token1,
  [2121] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(342), 1,
      aux_sym_inline_text_token1,
  [2128] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(344), 1,
      sym_expression,
  [2135] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(346), 1,
      sym_expression,
  [2142] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(348), 1,
      aux_sym_inline_text_token1,
  [2149] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      aux_sym_tag_name_token1,
  [2156] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      sym__indent,
  [2163] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(354), 1,
      aux_sym_inline_text_token1,
  [2170] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(356), 1,
      sym_expression,
  [2177] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(358), 1,
      anon_sym_SPACE,
  [2184] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(360), 1,
      sym_expression,
  [2191] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(362), 1,
      aux_sym_inline_text_token1,
  [2198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(364), 1,
      aux_sym_tag_name_token1,
  [2205] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(366), 1,
      aux_sym_inline_text_token1,
  [2212] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(368), 1,
      aux_sym_inline_text_token1,
  [2219] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      ts_builtin_sym_end,
  [2226] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(372), 1,
      anon_sym_SPACE,
  [2233] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_SPACE,
  [2240] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(376), 1,
      anon_sym_SPACE,
  [2247] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(378), 1,
      anon_sym_SPACE,
  [2254] = 2,
    ACTIONS(287), 1,
      sym_comment,
    ACTIONS(380), 1,
      anon_sym_SPACE,
  [2261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym__indent,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 92,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 178,
  [SMALL_STATE(7)] = 218,
  [SMALL_STATE(8)] = 258,
  [SMALL_STATE(9)] = 304,
  [SMALL_STATE(10)] = 350,
  [SMALL_STATE(11)] = 390,
  [SMALL_STATE(12)] = 433,
  [SMALL_STATE(13)] = 476,
  [SMALL_STATE(14)] = 506,
  [SMALL_STATE(15)] = 536,
  [SMALL_STATE(16)] = 557,
  [SMALL_STATE(17)] = 578,
  [SMALL_STATE(18)] = 599,
  [SMALL_STATE(19)] = 620,
  [SMALL_STATE(20)] = 641,
  [SMALL_STATE(21)] = 662,
  [SMALL_STATE(22)] = 683,
  [SMALL_STATE(23)] = 704,
  [SMALL_STATE(24)] = 725,
  [SMALL_STATE(25)] = 746,
  [SMALL_STATE(26)] = 774,
  [SMALL_STATE(27)] = 802,
  [SMALL_STATE(28)] = 827,
  [SMALL_STATE(29)] = 852,
  [SMALL_STATE(30)] = 877,
  [SMALL_STATE(31)] = 902,
  [SMALL_STATE(32)] = 924,
  [SMALL_STATE(33)] = 946,
  [SMALL_STATE(34)] = 968,
  [SMALL_STATE(35)] = 990,
  [SMALL_STATE(36)] = 1008,
  [SMALL_STATE(37)] = 1030,
  [SMALL_STATE(38)] = 1052,
  [SMALL_STATE(39)] = 1074,
  [SMALL_STATE(40)] = 1096,
  [SMALL_STATE(41)] = 1118,
  [SMALL_STATE(42)] = 1136,
  [SMALL_STATE(43)] = 1158,
  [SMALL_STATE(44)] = 1180,
  [SMALL_STATE(45)] = 1202,
  [SMALL_STATE(46)] = 1221,
  [SMALL_STATE(47)] = 1240,
  [SMALL_STATE(48)] = 1257,
  [SMALL_STATE(49)] = 1274,
  [SMALL_STATE(50)] = 1291,
  [SMALL_STATE(51)] = 1308,
  [SMALL_STATE(52)] = 1325,
  [SMALL_STATE(53)] = 1342,
  [SMALL_STATE(54)] = 1359,
  [SMALL_STATE(55)] = 1376,
  [SMALL_STATE(56)] = 1392,
  [SMALL_STATE(57)] = 1408,
  [SMALL_STATE(58)] = 1424,
  [SMALL_STATE(59)] = 1440,
  [SMALL_STATE(60)] = 1456,
  [SMALL_STATE(61)] = 1472,
  [SMALL_STATE(62)] = 1488,
  [SMALL_STATE(63)] = 1504,
  [SMALL_STATE(64)] = 1520,
  [SMALL_STATE(65)] = 1536,
  [SMALL_STATE(66)] = 1552,
  [SMALL_STATE(67)] = 1568,
  [SMALL_STATE(68)] = 1584,
  [SMALL_STATE(69)] = 1600,
  [SMALL_STATE(70)] = 1616,
  [SMALL_STATE(71)] = 1632,
  [SMALL_STATE(72)] = 1648,
  [SMALL_STATE(73)] = 1664,
  [SMALL_STATE(74)] = 1680,
  [SMALL_STATE(75)] = 1696,
  [SMALL_STATE(76)] = 1712,
  [SMALL_STATE(77)] = 1728,
  [SMALL_STATE(78)] = 1744,
  [SMALL_STATE(79)] = 1760,
  [SMALL_STATE(80)] = 1776,
  [SMALL_STATE(81)] = 1792,
  [SMALL_STATE(82)] = 1808,
  [SMALL_STATE(83)] = 1824,
  [SMALL_STATE(84)] = 1841,
  [SMALL_STATE(85)] = 1857,
  [SMALL_STATE(86)] = 1873,
  [SMALL_STATE(87)] = 1889,
  [SMALL_STATE(88)] = 1905,
  [SMALL_STATE(89)] = 1918,
  [SMALL_STATE(90)] = 1931,
  [SMALL_STATE(91)] = 1942,
  [SMALL_STATE(92)] = 1955,
  [SMALL_STATE(93)] = 1968,
  [SMALL_STATE(94)] = 1981,
  [SMALL_STATE(95)] = 1990,
  [SMALL_STATE(96)] = 2003,
  [SMALL_STATE(97)] = 2016,
  [SMALL_STATE(98)] = 2029,
  [SMALL_STATE(99)] = 2042,
  [SMALL_STATE(100)] = 2055,
  [SMALL_STATE(101)] = 2065,
  [SMALL_STATE(102)] = 2073,
  [SMALL_STATE(103)] = 2081,
  [SMALL_STATE(104)] = 2089,
  [SMALL_STATE(105)] = 2097,
  [SMALL_STATE(106)] = 2107,
  [SMALL_STATE(107)] = 2114,
  [SMALL_STATE(108)] = 2121,
  [SMALL_STATE(109)] = 2128,
  [SMALL_STATE(110)] = 2135,
  [SMALL_STATE(111)] = 2142,
  [SMALL_STATE(112)] = 2149,
  [SMALL_STATE(113)] = 2156,
  [SMALL_STATE(114)] = 2163,
  [SMALL_STATE(115)] = 2170,
  [SMALL_STATE(116)] = 2177,
  [SMALL_STATE(117)] = 2184,
  [SMALL_STATE(118)] = 2191,
  [SMALL_STATE(119)] = 2198,
  [SMALL_STATE(120)] = 2205,
  [SMALL_STATE(121)] = 2212,
  [SMALL_STATE(122)] = 2219,
  [SMALL_STATE(123)] = 2226,
  [SMALL_STATE(124)] = 2233,
  [SMALL_STATE(125)] = 2240,
  [SMALL_STATE(126)] = 2247,
  [SMALL_STATE(127)] = 2254,
  [SMALL_STATE(128)] = 2261,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(20),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(45),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(29),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(124),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(27),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(27),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(125),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(126),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 1, .production_id = 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, .production_id = 1),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(17),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(46),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(28),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(127),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(30),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(30),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(116),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(123),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(5),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, .production_id = 1),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, .production_id = 1),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(112),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(85),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(119),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(86),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_or_id, 2),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_or_id, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 4),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_name, 1),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 2),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 3),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 3),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mixin, 3, .production_id = 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mixin, 3, .production_id = 4),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 1),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, .production_id = 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, .production_id = 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 3),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 3),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop, 3),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop, 3),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mixin, 4, .production_id = 4),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mixin, 4, .production_id = 4),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, .production_id = 6),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, .production_id = 6),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_text, 2),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_text, 2),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, .production_id = 3),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, .production_id = 3),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 3),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, .production_id = 7),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, .production_id = 7),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, .production_id = 8),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, .production_id = 8),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indented_block, 4),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_indented_block, 4),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mixin, 5, .production_id = 4),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mixin, 5, .production_id = 4),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 4),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 2),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 2),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 4),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 4),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 3),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 3),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional, 2),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 2),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_loop, 4),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_loop, 4),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, .production_id = 5),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, .production_id = 5),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, .production_id = 1),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_name, 1),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [321] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2), SHIFT_REPEAT(95),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, .production_id = 9),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [344] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [346] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [356] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [360] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [370] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
  },
  [5] = {
    [ts_external_token__indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_pug_external_scanner_create(void);
void tree_sitter_pug_external_scanner_destroy(void *);
bool tree_sitter_pug_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_pug_external_scanner_serialize(void *, char *);
void tree_sitter_pug_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_pug(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_pug_external_scanner_create,
      tree_sitter_pug_external_scanner_destroy,
      tree_sitter_pug_external_scanner_scan,
      tree_sitter_pug_external_scanner_serialize,
      tree_sitter_pug_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
